server:
 port : 9003
 
 
spring:
   application:
          name: advertise-service
   config:
          import: configserver:http://localhost:8888
   zipkin: 
      base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true                
                

      
management:
  endpoints:
    web:
      exposure:
        include: "*"  
            
  health:
     circuitbreakers:
      enabled: true
  endpoint:
     health:
       show-details: always      
      
resilience4j:
  circuitbreaker:
    instances:
      default:
          registerHealthIndicator: true
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 5s      
      STATUS-FROM-MASTER-DATA-SERVICE:
          registerHealthIndicator: true
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 10s
      TOKEN-VALIDATION-SERVICE:
          registerHealthIndicator: true
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 10s
         

                