server: 
   port: 9002
   
spring:
   application:
          name: masterdata-service
   config:
          import: configserver:http://localhost:8888
          
   zipkin: 
      base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
management:
 endpoints:
   web:
     exposure:
        include: "*"                    